// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8p1Nh61Xkf0ZInROuLUqS7kzLw2ydaBI',
    appId: '1:891464398638:web:056cf80039ecf6cc792cbf',
    messagingSenderId: '891464398638',
    projectId: 'jobportal-9d822',
    authDomain: 'jobportal-9d822.firebaseapp.com',
    storageBucket: 'jobportal-9d822.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpvlC3poR96GEypPk3oYYmDZy7wQbngzs',
    appId: '1:891464398638:android:ddd09a72245065ce792cbf',
    messagingSenderId: '891464398638',
    projectId: 'jobportal-9d822',
    storageBucket: 'jobportal-9d822.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFXdLvuFF7lwF2nycCYSh7jzpc8AlkzTI',
    appId: '1:891464398638:ios:d561fc4c8e4f62ca792cbf',
    messagingSenderId: '891464398638',
    projectId: 'jobportal-9d822',
    storageBucket: 'jobportal-9d822.firebasestorage.app',
    iosBundleId: 'com.ralfiz.jobPortal',
  );
}
